package com.example.util;

import javax.sql.DataSource;
import java.sql.*;

public class DbUtil {
    public static void initSchema(DataSource ds) {
        String userTable = "CREATE TABLE IF NOT EXISTS users (" +
                "login VARCHAR(64) PRIMARY KEY, " +
                "nickname VARCHAR(64) NOT NULL, " +
                "password_hash VARCHAR(128) NOT NULL)";

        // H2 v2 in PostgreSQL mode does not understand the generic IDENTITY keyword
        String scoresTable = "CREATE TABLE IF NOT EXISTS scores (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "nickname VARCHAR(64) NOT NULL, " +
                "score INT NOT NULL, " +
                "played_at TIMESTAMP NOT NULL)";

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute(userTable);
            st.execute(scoresTable);
        } catch (SQLException e) {
            throw new RuntimeException("Schema init failed", e);
        }
    }
}